# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 21:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
