# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Need')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='need',
            name='resources',
            field=models.ManyToManyField(through='api.ResourceBookmark', to='api.Resource'),
        ),
    ]
