# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170605_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedResourceMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcebookmark',
            name='need',
        ),
        migrations.RemoveField(
            model_name='resourcebookmark',
            name='resource',
        ),
        migrations.AlterField(
            model_name='need',
            name='resources',
            field=models.ManyToManyField(through='api.NeedResourceMatch', to='api.Resource'),
        ),
        migrations.DeleteModel(
            name='ResourceBookmark',
        ),
        migrations.AddField(
            model_name='needresourcematch',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Need'),
        ),
        migrations.AddField(
            model_name='needresourcematch',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
    ]
