# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170609_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='status',
        ),
    ]
