# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 18:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170623_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
