# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170809_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
