# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_client_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
