# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170819_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.AddField(
            model_name='provider',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='referrer',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
